version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: tail -f /dev/null  # Keeps the container running in idle mode
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  db_data:
